### ISSUE TITLE
'SfincsModel' object has no attribute 'setup_wind_forcing'

### ISSUE THREAD

**Issue by CarsonW503** [Deltares/hydromt_sfincs#113]
Hey this may be a goofy issue since I'm relatively new to Python but I can't seem to find a way around it so I'd love some help/clarification on why I'm getting the following error: 'SfincsModel' object has no attribute 'setup_wind_forcing'

I'm looking to apply a spatially uniform wind field and the function 'setup_wind_forcing' is exactly what I need, however there doesn't appear that hydromt_sfincs has that function when I try and use it. I see the online documentation for it, all my packages are up to date, and I yet I don't seem to able to use that function. I'm able to use 'setup_waterlevel_forcing' just fine but not this... I'm hoping this is just a simple error on my side. 

Thanks a ton :)

<img width="467" alt="Screenshot 2023-07-26 174016" src="https://github.com/Deltares/hydromt_sfincs/assets/114448216/aef0dcbf-b952-4c88-9f36-3e5819f5f76d">

<img width="470" alt="Screenshot 2023-07-26 173905" src="https://github.com/Deltares/hydromt_sfincs/assets/114448216/9fe61357-6ab7-49a4-b167-7c43781d14c5">

**Comment by roeldegoede** [comment]
Hi there! Thanks for your question.

The setup_wind_forcing is a function that has been added since the last official release (version 1.0.0). If you installed HydroMT-SFINCS from conda-forge or PyPi, this is the version that will be installed. In the meantime, quite some bugfixes and additions have taken place, [see here](https://deltares.github.io/hydromt_sfincs/latest/changelog.html).

To be able to work with the current "main" branch, or even a different branch, you need a developers install. That basically entails that you make a clone of the desired branch on your machine, and install that clone in your Python environment. This is explained [here](https://deltares.github.io/hydromt_sfincs/latest/dev_guide/dev_install.html). Note that if you already have an environment, you basically only have to do the cloning and then installing your clone with "pip install -e YOURPATH/hydromt_sfincs".

At the moment, we are working towards a next release (version 1.0.1). From that point onwards, the setup_wind_forcing should also work after a normal installation.

**Comment by roeldegoede** [comment]
@CarsonW503 we recently released HydroMT-SFINCS v1.0.1. So if you update your HydroMT-SFINCS version, (and make sure you have hydromt > 0.8.0), this functionality should work. Please let me know if that is not the case.

Cheers,
Roel
