### ISSUE TITLE
Some suggestions for improving the user guide and example sections

### ISSUE THREAD

**Issue by jkiesel1988** [Deltares/hydromt_sfincs#118]
Dear developers, dear Dirk and Tim,
while going through the "Example: Build from Script" (https://deltares.github.io/hydromt_sfincs/latest/_examples/build_from_script.html) I encountered some issues and questions that may help you to improve the online documentation of hydromt-sfincs. 

1. In section 3 (# Add depth information to modelgrid based on these chosen datasets), I was wondering how hydromt interpolates missing data when using separate bathymetry and elevation files for interpolating the .dep file. Due to often coarse resolutions, elevation and bathymetry may not overlap and data gaps exist. I believe it could be helpful for the user to learn directly in the example how such gaps are handled by hyromt.
2. In section 7, I had troubles figuring out how to use a reclassification table when implementing the spatially varying surface roughness from  a landcover raster. It is indeed explained that such a table can be used, but an example on how it needs to look like (e.g. its attribute table to match the land cover raster) and how to call it from hydromt would be helpful. I think an example for the different methods to implement the manning coefficients (landcover + reclass table & landcover raster that already contains the manning coefficients) would be beneficial for the user. 
3. I encountered the issue that the version of hydromt that I used was not yet able to execute the sf.setup_subgrid command of section 8. I believe it would be helpful for the user to make it clearer directly at the beginning that the example corresponds to a specific version of hydromt and that some commands may not work with older versions.   
4. Waterlevel timeseries forcing, section 10: I have troubles implementing the waterlevel timeseries forcing, which I provide in the data catalog as GeoDataset with vector driver (a csv containing the coordinates of the forcing location and a csv containing the waterlevel timeseries). I think it would be helpful if the "Example: Build from Script" contains some examples of implementing a waterlevel timeseries from "real data" instead of making the timeseries up. I also seem to have a problem with reading the GeoDataset from the data catalog (getting this as error message: ValueError: x dimension "None" not found in columns: Index([' x', ' y'], dtype='object'), even though my files look similar to the ones provided in the example "Prepare a data catalog". It might just be me, but I believe it could help the users to get a bit more explanation on the preparation and usage of the data type GeoDataset (and other such as netcdf) for implementing waterlevel (and waves) timeseries. 

I hope these points are useful for you. In case you have any further questions, please dont hesitate to contact me.
Cheers,
Joshua

**Comment by roeldegoede** [comment]
Hi Joshua, 

Thanks a lot for the feedback provided on the examples. Though we just released a newer version of HydroMT-SFINCS, updating (and especially improving) the examples is on our list for a next release! Therefore your feedback is much appreciated and we will take it into account while updating the examples. 

Regarding your questions:
1. You are right that this should be more clearly specified. Before we really demanded that the input data should cover the entire grid, and then you could specify buffer cells that formed a transition zone between the datasets, where the interp_method was applied as interpolation method. Recent changes in the code also allow for "non-complete" inputs, and then the rio_idw method is applied as interpolation function for the cells with missing values. The latest changes in hydromt also allow for extrapolation, where "nearest" is used.
2. Agree on this as well. There are already some example csv-files (e.g. vito, corine etc.) that show the mapping from landuse to N (manning) here: https://github.com/Deltares/hydromt_sfincs/tree/main/hydromt_sfincs/data/lulc
3. Latest additions to the examples, the burning in of rivers, does require hydromt > 0.8.0. That has been changed since the recent release in the pyprojct.toml, but we should add this to the notebooks indeed! We sort of did this already in build_from_cli, but specifying the specific needed version makes it much clearer.
4. In the example build_from_cli, we use a real dataset or setup_waterlevel_forcing coming from the global tide and surge model (and present in the artifact data). You could try to implement that one in the build_from_script example and then compare it to your dataset? 

Cheers,
Roel

**Comment by jkiesel1988** [comment]
Dear Roel, 
thanks a lot for your quick and very helpful reply!
I don't want to spam you with too many questions but I would have two more inquiries, which might also be relevant for other users. The first deals again with the implementation of manning roughness coefficients. It seems that I have a problem with the NoData value in my landuse raster/reclass table. Here comes the format of my reclass_table:

index,class,N
1,1100,0.06
2,1110,0.06
3,1120,0.06
...
14,-3.4e+38
When first prompting datasets_rgh = [{"lulc": "landcover", "reclass_table": "man_mod"}] and then setup_manning_roughness, hydromt answers: "The nodata value None is not in the reclass table.None will be used for the params." I have tried many variations of the above No Data value but nothing worked so far. Can you suspect what the problem is?

Second, in the build from script example (https://deltares.github.io/hydromt_sfincs/latest/_examples/build_from_cli.html) under 6. the (very, very long) output of the command "!hydromt update sfincs tmp_sfincs_base -i sfincs_base_update.yml -v" is printed. Is that on purpose? I am not sure if I can use the artifact data in my case, as it only covers the Piave basin, right? I am currently building my own model (for Naples, Italy) based on the example tutorial (Build a model from Python). I could imagine that providing some examples on how users can implement their own (water level) forcing from script of the various datasources (netcdf, csv) could be very helpful. But I might have also missed some examples on Github for that. 
Sorry for the long mail and many thanks again for your time and help. This is much appreciated.
Best wishes,
Joshua

**Comment by jkiesel1988** [comment]
Hi Roel, 
I really appreciated your reply, thanks again. This is just to let you know that I discussed the above issues with Dirk today and he found that the problem with my reclass table was basically the missing definition of the driver_kwargs: index_col, which should guide towards the column containing the actual landcover classes. 
The problem I had with setting up the waterlevel forcing was caused by spaces that Dirk found in the csv file that contains the station coordinates. Thats why the data could not be read by hydromt. 
Many thanks to the two of you and looking forward to continue my journey through hydromt.
Best wishes,
Joshua
