### ISSUE TITLE
Plot_basemap extent and dep interpolation issue

### ISSUE THREAD

**Issue by sinyeekoh** [Deltares/hydromt_sfincs#139]
Hi,

I am new to Sfincs and currently have two issues with a SFINCS model:

1. Plot_basemap extent: I setup a grid with the following coordinates (x0 = 59500, y0 = 3776400, epsg = 32654). However the basemap function doesn't show the full model extent:

![image](https://github.com/Deltares/hydromt_sfincs/assets/148735419/c339e2d7-58a0-46c1-ae90-13e563a6080e)

![image](https://github.com/Deltares/hydromt_sfincs/assets/148735419/51830f59-ced5-4331-8265-728f3b8e6393)

2. Dep file interpolation: I use the setup_dep function and found out the dep file interpolation is weird and the dep map doesn't change even when the zmax is changed from 10m to 5m. 

Example of zmax is 10m:
![image](https://github.com/Deltares/hydromt_sfincs/assets/148735419/88eb3250-ca57-4190-88e6-89a62f21439e)

When the zmax is 2m:
![image](https://github.com/Deltares/hydromt_sfincs/assets/148735419/0554ea2c-3473-48a5-a250-38ed96d710f1)

The elevation at white region is more than 10m and should be excluded from the depth file and mask region. However it is included in the dep file and mask file currently in my model. Is there a way to solve this issue? 

I am using SFINCS_v2.0.0+AlpeHuez_release. Thanks.

**Comment by roeldegoede** [comment]
Dear @sinyeekoh,

The plot_basemap extent does remind me of #123 . A quickfix was proposed there, and we'll ahve to figure out a neat way of fixing this in future releases. Hopefully this quickfix works for you. Let me know if that is not the case.

The dep file interpolation is not weird, but you should use it in a different way. Once you created a grid, you can use `setup_dep` to add elevation data to this grid. If your data covers your entire grid (or at least the area that you want to model), you could use just one dataset. Often, you want to merge different datasets (e.g. one for topography and one for bathymetry). When that is the case, you can provide arguments like zmin and zmax per dataset, to describe where and when a dataset may be applied. 

In your case, you have one dataset and you lower the zmax from 10 to 2. What I see in the dep-map is that no more values are found above 2m elevation, whereas all values <2m remain equal. Since we need data everywhere the mask is active, HydroMT-SFINCS fills the rest of the grid by extrapolating, hence you see a lot of 2s.

So what you should do is first `setup_dep`, and when using just one dataset, zmin and zmax are not recommended to use. Then you can set your mask using `setup_mask_active` for which you can provide a zmin and zmax. Here, zmax=2 would mean a smaller domain than zmax=10, but this selection can only be made when you specified elevation data on your enitre grid beforehand.

Last but not least, there is already a newer version of SFINCS, [see here](https://download.deltares.nl/sfincs), and also make sure you are using the latest HydroMT-SFINCS. We are aware of some bugs (see open issues and pull-requests), and also some bugs have already been fixed in the main branch. 

Cheers

**Comment by roeldegoede** [comment]
@sinyeekoh I assume the above answer solved your issues, if not, let us know.
