### ISSUE TITLE
mod.results['zsmax'] returns values much smaller than np.nanmax(mod.results['zs'])

### ISSUE THREAD

**Issue by TPCollings** [Deltares/hydromt_sfincs#154]
### HydroMT-SFINCS version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT-SFINCS.

### Reproducible Example

If you want to reproduce it, download this [model run folder](https://drive.google.com/file/d/1mILeFjPxQG8qaPrSnxEyn8-vmqqsPEF7/view?usp=drive_link), and run the following code, replacing `sfincs_event_path` for the directory to the downloaded model folder:

```
mod = SfincsModel(sfincs_event_path, mode="r")
mod.read_results()

zsmax = mod.results['zsmax']
zsmax_alt = mod.results['zs'].max('time',skipna=True)

print('zs_max = ' + str(np.nanmax(zsmax.values)))
print('alternative zsmax = ' +str(np.nanmax(zsmax_alt.values)))
```

### Current behaviour

```
zs_max = 1.4580437
alternative zsmax = 7.2471085
```

### Desired behaviour

That the zsmax variable is similar or the same as taking zsmax from the max of the zs variables. 

I have produced a gif of the event and checked input BCs and the event appears to simulating as expected. There just seems to be a bug in the zsmax variable.

**Comment by roeldegoede** [comment]
Thanks for bringing up this issue @TPCollings. I do agree that this behavior is unexpected. You indeed expect the zsmax variable to be similar (or larger) than the max of the instantaneous zs. However, I expect this issue to be unrelated to HydroMT-SFINCS since we only read-in SFINCS output using xarray, without further processing. 

I’ll try to find some time and see if I can find the problem in SFINCS.  I’ll keep you posted!

**Comment by TPCollings** [comment]
Thanks Roel, that solved it!
