### ISSUE TITLE
Metrics to evaluate the inundation model against some satellite or benchmark dataset

### ISSUE THREAD

**Issue by Jiangchao3** [Deltares/hydromt_sfincs#175]
### Kind of request

Adding new functionality

### Enhancement Description

Hi @roeldegoede and @DirkEilander ,

Once complete the simulation and get the inundation map, **how to evaluate model's performance especially the flood inundation extent against some existing dataset like satellite or benchmark map?** I just notice the hydromt-sfincs framework can output the discharge time series at some croos section or water depth, **don't see any function to evaluate the inundation map via comparing model to some satellite image from space**. 

FYI, previouse study use the metrics such as **Hit rate,  False alarm ratio , Critical Success Index** to assess the modeling result.
See the reference here: 
1. https://www.seamlesswave.com/metrics.html
2. https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2017WR020917

I believe using some satellite data to validate or evaluate inundation model is very common method in practice.

Looking forward to your feedback!

Jiangchao

**Comment by roeldegoede** [comment]
Hi @Jiangchao3,

Thank you for this great suggestion! With the `hydromt_sfincs.utils.downscale_floodmap`, we provide the possibility to downscale your floodmap to a higher-resolution DEM. But indeed, that doesn't yet tell us how well the results resemble the truth.

I agree that it would be nice to have some standard validation methods in HydroMT-SFINCS, both for the gridded outputs as well as for the timeseries output. The methods you propose are very suitable for this, but we didn't standardize this (yet), mainly because observed flood extents come in many different formats (and are scarce). 

You can already find some work done by Dirk on this topic [here](https://github.com/DirkEilander/compound_flood_modelling/blob/main/2_code/4_analyze_plot/skill.py).  It is on our list to add this to HydroMT-SFINCS at some point, but feel free to contribute to this and add it to HydroMT-SFINCS in the meantime!

**Comment by Jiangchao3** [comment]
Thanks for your reply @roeldegoede
