### ISSUE TITLE
create script for downscaling of floodmaps - yes rotated - but no VRT

### ISSUE THREAD

**Issue by roeldegoede** [Deltares/hydromt_sfincs#71]

**Comment by roeldegoede** [comment]
Will be a script that creates a floodmap based on
- netcdf output
and
- geotiff/list of geotiffs/VRT 
- or webmercator tiles (topobathy and index)

**Comment by DirkEilander** [comment]
Instead of writing geotif tiles and a VRT in the subgrid routine, we could also write each tile directly to a single (large!) cloud optimized geotif using rasterio, [see docs](https://rasterio.readthedocs.io/en/latest/topics/windowed-rw.html#writing). Potentially even adding overviews (i.e. internal zoomlevels). This would also work for rotated grids and is fast to load for visualization in e.g. QGIS.

**Comment by lgrimley** [comment]
@DirkEilander does your idea relate to the zoom netcdf files that the subgrid is currently built from using DDB/OET? Maarten has a python script to create those netcdf files with zoom levels pretty quick and I've found them pretty efficient.

**Comment by roeldegoede** [comment]
@lgrimley you mean the netcdf tiles that you can use while setting up your model?

We are supporting those in hydromt_sfincs as well, but we first need to create a VRT per zoomlevel to be able to read the dataset
